"""
FillerAudioPlayer — T047 + T050 / US5

Pre-loads WAV filler clips into memory and provides async play() and cancel()
methods. Filler audio masks Tier 3/4 processing latency (>200ms) with
human-sounding bridging sounds ("Hmm...", "Aah...") so the conversation
feels natural rather than frozen.

Filler-to-tier mapping (T050):
  - Tier 3 / manipulation_pattern → hmm  (reflective pause)
  - Tier 4 / truth_conflict        → aah  (considered pause)
  - emotional_spike                → right_so

Data directory: data/filler_audio/ (WAV files generated by T016/T017).
Supported names: hmm, aah, right_so, interesting, cool_but.
"""

from __future__ import annotations

import asyncio
import logging
import time
import wave
from dataclasses import dataclass, field
from pathlib import Path
from typing import Final, Optional

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Filler-to-trigger mapping (T050)
# ---------------------------------------------------------------------------

# Maps tier trigger_type to filler clip name.
TRIGGER_FILLER_MAP: Final[dict[str, str]] = {
    "manipulation_pattern": "hmm",    # Tier 3 — reflective pause
    "truth_conflict": "aah",          # Tier 4 — considered pause
    "emotional_spike": "right_so",    # High-energy deflection
    "sincere_pivot": "cool_but",      # Genuine reset / apology — warmth shift
    "high_m_entry": "interesting",    # m crosses into high zone — engagement lift
    "warm_tone": "right_so",          # Tier 1 warm tone detected
}

# Latency threshold after which filler is queued (ms)
FILLER_LATENCY_THRESHOLD_MS: Final[float] = 200.0


# ---------------------------------------------------------------------------
# FillerAudioPlayer
# ---------------------------------------------------------------------------

@dataclass
class FillerAudioPlayer:
    """
    Pre-loads WAV filler clips and plays them asynchronously.

    Filler clips are loaded once at construction into memory (bytes) to
    avoid disk I/O during latency-critical turns. play() streams the
    pre-loaded bytes over the WebSocket the same way Gemini audio chunks
    are sent, so the browser hears them in real time.

    Attributes:
        data_dir: Path to the filler audio data directory.
        _clips: Dict mapping clip names to raw PCM bytes (post-header strip).
        _active_task: Currently running play task (None if idle).
        _websocket: Client WebSocket for audio output. Set via set_websocket()
            when a session connects. None means output is suppressed (test mode).

    Usage:
        player = FillerAudioPlayer(data_dir=Path("data/filler_audio"))
        player.load()
        player.set_websocket(websocket)      # call when session connects

        # Queue filler for Tier 3 processing
        clip = player.clip_for_trigger("manipulation_pattern")
        await player.play(clip)

        # Cancel if user speaks during playback (T051)
        player.cancel()
    """

    data_dir: Path = field(default_factory=lambda: Path("data/filler_audio"))

    # Internal state
    _clips: dict[str, bytes] = field(default_factory=dict, init=False, repr=False)
    _active_task: Optional[asyncio.Task] = field(default=None, init=False, repr=False)
    _websocket: Optional[object] = field(default=None, init=False, repr=False)
    _filler_active: asyncio.Event = field(default_factory=asyncio.Event, init=False, repr=False)

    def set_websocket(self, websocket: Optional[object]) -> None:
        """
        Attach (or detach) the client WebSocket for audio output.

        Called by WillowAgent when a session connects/disconnects.
        None suppresses audio output without raising errors (test mode).
        """
        self._websocket = websocket

    def load(self) -> None:
        """
        Pre-load all WAV files from data_dir into memory.

        Strips the WAV header and retains only the raw PCM payload.
        Silently skips missing files so a partial audio set does not
        crash the agent at startup.
        """
        clip_names = ["hmm", "aah", "right_so", "interesting", "cool_but"]

        for name in clip_names:
            wav_path = self.data_dir / f"{name}.wav"
            if not wav_path.exists():
                logger.debug("Filler clip not found, skipping: %s", wav_path)
                continue
            try:
                with wave.open(str(wav_path), "rb") as wf:
                    raw_pcm = wf.readframes(wf.getnframes())
                self._clips[name] = raw_pcm
                logger.debug(
                    "Loaded filler clip '%s': %d bytes PCM",
                    name, len(raw_pcm),
                )
            except Exception as exc:
                logger.warning("Failed to load filler clip '%s': %s", name, exc)

        logger.info(
            "FillerAudioPlayer loaded %d/%d clips from %s",
            len(self._clips), len(clip_names), self.data_dir,
        )

    def clip_for_trigger(self, trigger_type: str) -> str:
        """
        Return the filler clip name for a given trigger type (T050).

        Falls back to 'hmm' for unknown trigger types.

        Args:
            trigger_type: One of manipulation_pattern, truth_conflict,
                emotional_spike.

        Returns:
            Clip name string suitable for passing to play().
        """
        return TRIGGER_FILLER_MAP.get(trigger_type, "hmm")

    async def play(self, clip_name: str) -> bool:
        """
        Play a filler clip asynchronously.

        Starts playback as an asyncio.Task stored in _active_task.
        Callers can cancel via cancel(). In the real audio pipeline,
        this method would stream raw_pcm bytes to the audio output device
        or Gemini Live output channel. Here it simulates playback duration
        via asyncio.sleep based on PCM byte count at 16kHz/16-bit/mono.

        Args:
            clip_name: Name of the clip to play (e.g. "hmm").

        Returns:
            True if clip started, False if clip not loaded.
        """
        logger.info(f"FILLER PLAYING: clip={clip_name}")
        raw_pcm = self._clips.get(clip_name)
        if raw_pcm is None:
            logger.debug("Filler clip '%s' not loaded — skipping playback", clip_name)
            return False

        # Cancel any in-progress filler before starting a new one
        self.cancel()

        self._active_task = asyncio.create_task(
            self._play_clip(clip_name, raw_pcm),
            name=f"filler:{clip_name}",
        )
        return True

    def cancel(self) -> bool:
        """
        Cancel active filler playback (T051 — VAD-based cancellation).

        Called from InterruptionHandler when user speech is detected
        while a filler clip is playing, or when Gemini's real audio
        starts streaming to avoid overlap.

        Returns:
            True if a task was cancelled, False if nothing was playing.
        """
        cancelled = False
        if self._active_task and not self._active_task.done():
            logger.debug("Canceling active filler audio playback")
            self._active_task.cancel()
            cancelled = True
        
        # Ensure state is cleared immediately even if task cancellation 
        # is still propagating through the event loop
        self._filler_active.clear()
        return cancelled

    @property
    def is_playing(self) -> bool:
        """Return True if filler audio is currently playing."""
        return self._filler_active.is_set()

    async def _play_clip(self, clip_name: str, raw_pcm: bytes) -> None:
        """
        Send PCM bytes to the client WebSocket in small chunks (FR-010, T048).

        Sends the clip in 20ms chunks — the same path Gemini audio chunks use. 
        The browser's AudioWorklet receives the bytes, decodes them as 
        16kHz/16-bit/mono PCM, and plays them immediately.

        Streaming in chunks allows cancellation (barge-in or real Gemini audio
        starting) to actually stop the network transfer and browser playback,
        preventing audio overlap.
        """
        # 16kHz * 2 bytes/sample * 1 channel = 32000 bytes per second
        duration_s = len(raw_pcm) / 32_000
        logger.debug(
            "Filler playback started: clip='%s' duration=%.0fms",
            clip_name, duration_s * 1000,
        )
        start = time.perf_counter()
        self._filler_active.set()

        chunk_size = 640   # 20ms of PCM data (32000 bytes/s * 0.020)
        sleep_duration = 0.020
        
        try:
            ws = self._websocket
            for i in range(0, len(raw_pcm), chunk_size):
                chunk = raw_pcm[i:i+chunk_size]
                if ws is not None:
                    try:
                        if hasattr(ws, 'send_bytes'):
                            await ws.send_bytes(chunk)   # FastAPI WebSocket
                        else:
                            await ws.send(chunk)         # websockets library
                    except Exception as exc:
                        logger.debug("Filler WebSocket send failed: %s", exc)
                        break
                
                # Check cancellation between chunks
                await asyncio.sleep(sleep_duration)
            
            elapsed = (time.perf_counter() - start) * 1000
            logger.debug(
                "Filler playback completed naturally: clip='%s' elapsed=%.0fms",
                clip_name, elapsed,
            )
            
        except asyncio.CancelledError:
            elapsed = (time.perf_counter() - start) * 1000
            logger.info(
                "Filler playback canceled at %.0fms (cut short by %dms)",
                elapsed, (duration_s * 1000) - elapsed,
            )
            # Re-raise so the task resolves properly
            raise
        finally:
            self._filler_active.clear()

    def get_loaded_clips(self) -> list[str]:
        """Return sorted list of successfully loaded clip names."""
        return sorted(self._clips.keys())
