"""
FillerAudioPlayer — T047 + T050 / US5

Pre-loads WAV filler clips into memory and provides async play() and cancel()
methods. Filler audio masks Tier 3/4 processing latency (>200ms) with
human-sounding bridging sounds ("Hmm...", "Aah...") so the conversation
feels natural rather than frozen.

Filler-to-tier mapping (T050):
  - Tier 3 / manipulation_pattern → hmm  (reflective pause)
  - Tier 4 / truth_conflict        → aah  (considered pause)
  - emotional_spike                → right_so

Data directory: data/filler_audio/ (WAV files generated by T016/T017).
Supported names: hmm, aah, right_so, interesting, cool_but.
"""

from __future__ import annotations

import asyncio
import logging
import time
import wave
from dataclasses import dataclass, field
from pathlib import Path
from typing import Final, Optional

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Filler-to-trigger mapping (T050)
# ---------------------------------------------------------------------------

# Maps tier trigger_type to filler clip name.
TRIGGER_FILLER_MAP: Final[dict[str, str]] = {
    "manipulation_pattern": "hmm",    # Tier 3 — reflective pause
    "truth_conflict": "aah",          # Tier 4 — considered pause
    "emotional_spike": "right_so",    # High-energy deflection
}

# Latency threshold after which filler is queued (ms)
FILLER_LATENCY_THRESHOLD_MS: Final[float] = 200.0


# ---------------------------------------------------------------------------
# FillerAudioPlayer
# ---------------------------------------------------------------------------

@dataclass
class FillerAudioPlayer:
    """
    Pre-loads WAV filler clips and plays them asynchronously.

    Filler clips are loaded once at construction into memory (bytes) to
    avoid disk I/O during latency-critical turns. play() streams the
    pre-loaded bytes and returns a Task that can be cancelled if the user
    interrupts (T051).

    Attributes:
        data_dir: Path to the filler audio data directory.
        _clips: Dict mapping clip names to raw PCM bytes (post-header strip).
        _active_task: Currently running play task (None if idle).

    Usage:
        player = FillerAudioPlayer(data_dir=Path("data/filler_audio"))
        player.load()

        # Queue filler for Tier 3 processing
        clip = player.clip_for_trigger("manipulation_pattern")
        await player.play(clip)

        # Cancel if user speaks during playback (T051)
        player.cancel()
    """

    data_dir: Path = field(default_factory=lambda: Path("data/filler_audio"))

    # Internal state
    _clips: dict[str, bytes] = field(default_factory=dict, init=False, repr=False)
    _active_task: Optional[asyncio.Task] = field(default=None, init=False, repr=False)

    def load(self) -> None:
        """
        Pre-load all WAV files from data_dir into memory.

        Strips the WAV header and retains only the raw PCM payload.
        Silently skips missing files so a partial audio set does not
        crash the agent at startup.
        """
        clip_names = ["hmm", "aah", "right_so", "interesting", "cool_but"]

        for name in clip_names:
            wav_path = self.data_dir / f"{name}.wav"
            if not wav_path.exists():
                logger.debug("Filler clip not found, skipping: %s", wav_path)
                continue
            try:
                with wave.open(str(wav_path), "rb") as wf:
                    raw_pcm = wf.readframes(wf.getnframes())
                self._clips[name] = raw_pcm
                logger.debug(
                    "Loaded filler clip '%s': %d bytes PCM",
                    name, len(raw_pcm),
                )
            except Exception as exc:
                logger.warning("Failed to load filler clip '%s': %s", name, exc)

        logger.info(
            "FillerAudioPlayer loaded %d/%d clips from %s",
            len(self._clips), len(clip_names), self.data_dir,
        )

    def clip_for_trigger(self, trigger_type: str) -> str:
        """
        Return the filler clip name for a given trigger type (T050).

        Falls back to 'hmm' for unknown trigger types.

        Args:
            trigger_type: One of manipulation_pattern, truth_conflict,
                emotional_spike.

        Returns:
            Clip name string suitable for passing to play().
        """
        return TRIGGER_FILLER_MAP.get(trigger_type, "hmm")

    async def play(self, clip_name: str) -> bool:
        """
        Play a filler clip asynchronously.

        Starts playback as an asyncio.Task stored in _active_task.
        Callers can cancel via cancel(). In the real audio pipeline,
        this method would stream raw_pcm bytes to the audio output device
        or Gemini Live output channel. Here it simulates playback duration
        via asyncio.sleep based on PCM byte count at 16kHz/16-bit/mono.

        Args:
            clip_name: Name of the clip to play (e.g. "hmm").

        Returns:
            True if clip started, False if clip not loaded.
        """
        raw_pcm = self._clips.get(clip_name)
        if raw_pcm is None:
            logger.debug("Filler clip '%s' not loaded — skipping playback", clip_name)
            return False

        # Cancel any in-progress filler before starting a new one
        self.cancel()

        self._active_task = asyncio.create_task(
            self._play_clip(clip_name, raw_pcm),
            name=f"filler:{clip_name}",
        )
        return True

    async def _play_clip(self, clip_name: str, raw_pcm: bytes) -> None:
        """
        Internal coroutine: simulate PCM streaming duration.

        In production, replace this body with real audio output calls
        (e.g. push bytes to Gemini Live audio channel or sounddevice).
        Duration is calculated from byte count assuming 16kHz/16-bit/mono.
        """
        # 16kHz * 2 bytes/sample * 1 channel = 32000 bytes per second
        duration_s = len(raw_pcm) / 32_000
        logger.debug(
            "Filler playback started: clip='%s' duration=%.0fms",
            clip_name, duration_s * 1000,
        )
        start = time.perf_counter()
        try:
            await asyncio.sleep(duration_s)
            elapsed_ms = (time.perf_counter() - start) * 1000
            logger.debug(
                "Filler playback complete: clip='%s' elapsed=%.1fms",
                clip_name, elapsed_ms,
            )
        except asyncio.CancelledError:
            elapsed_ms = (time.perf_counter() - start) * 1000
            logger.debug(
                "Filler playback cancelled: clip='%s' after=%.1fms",
                clip_name, elapsed_ms,
            )
            raise

    def cancel(self) -> bool:
        """
        Cancel active filler playback (T051 — VAD-based cancellation).

        Called from InterruptionHandler when user speech is detected
        while a filler clip is playing.

        Returns:
            True if a task was cancelled, False if nothing was playing.
        """
        if self._active_task and not self._active_task.done():
            self._active_task.cancel()
            logger.debug("Filler playback cancelled by caller")
            return True
        return False

    @property
    def is_playing(self) -> bool:
        """True if a filler clip is currently in progress."""
        return (
            self._active_task is not None
            and not self._active_task.done()
        )

    def get_loaded_clips(self) -> list[str]:
        """Return sorted list of successfully loaded clip names."""
        return sorted(self._clips.keys())
